CREATE TABLE `disdukcapil`(
`NAMA_LGKP` varchar(250) NOT NULL,
`STAT_HBKEL` varchar(100) NOT NULL,
`AGAMA` varchar(20) NOT NULL,
`JENIS_PKRJN` varchar(50) NOT NULL,
`PDDK_AKH` varchar(150) NOT NULL,
`TMPT_LHR` varchar(50) NOT NULL,
`STATUS_KAWIN` varchar(20) NOT NULL,
`GOL_DARAH` varchar(5) NOT NULL,
`JENIS_KLMIN` varchar(10) NOT NULL,
`NO_KK` varchar(20) NOT NULL,
`NIK` varchar(20) NOT NULL,
`KAB_NAME` varchar(150) NOT NULL,
`NAMA_LGKP_AYAH` varchar(250) NOT NULL,
`NO_RW` varchar(5) NOT NULL,
`KEC_NAME` varchar(150) NOT NULL,
`NO_KEL` varchar(5) NOT NULL,
`NO_RT` varchar(5) NOT NULL,
`NO_KEC` varchar(5) NOT NULL,
`ALAMAT` varchar(250) NOT NULL,
`NO_PROP` varchar(5) NOT NULL,
`NAMA_LGKP_IBU` varchar(250) NOT NULL,
`PROP_NAME` varchar(150) NOT NULL,
`NO_KAB` varchar(5) NOT NULL,
`TGL_LHR` date DEFAULT NULL,
`KEL_NAME` varchar(150) NOT NULL, PRIMARY KEY (`NIK`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;